routes:
  /: home

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: blog
  /portfolio/:
    permalink: /portfolio/{slug}/
    template: projects
    filter: tag:project